name: productcrudapp actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: productcrudapp
  EKS_CLUSTER_NAME: productcrudapp-eks

jobs:
   Testing:
     runs-on: ubuntu-latest
     steps:
       - name: Code chekout
         uses: actions/checkout@v4

       - name: Maven test
         run: mvn test

   BUILD_AND_PUBLISH:
     needs: Testing
     runs-on: ubuntu-latest
     steps:
     - name: Code checkout
       uses: actions/checkout@v4

     - name: upload image to ECR
       uses: appleboy/docker-ecr-action@master
       with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          #cache_from: ${{ secrets.cache }}
          repo: ${{ env.ECR_REPOSITORY }}
          region: ${{ env.AWS_REGION }}
          tags: latest, ${{ github.run_number }}
          daemon_off: false
          dockerfile: ./Docker-files/app/Dockerfile
          context: ./